### ISSUE TITLE
استفاده در api token

### ISSUE THREAD

**Issue by hodhodan** [behnamnasehi/EncryptedSharedPreferences#1]
سلان وقت به خیر
عرض تشکر دارم
فقط یه سوال: 
آیا میشه از این روش برای ذخیره توکن هایی که از سرور میاد استفاده کرد؟
یعنی اگه کسی بتونه اپ ما رو دیکامپایل کنه، به این توکن که در اس پی به این روش ذخیره شده دسترسی داره؟

**Comment by behnamnasehi** [comment]
سلام بله میتونید استفاده کنید
خیر اکه دیکامپایل کنن بهش دسترسی نخواهند داشت
